version: '2'
services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'user'
      TZ: Asia/Tokyo
      restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      # - ./conf:/etc/mysql/conf.d
      # - ./logs:/var/log/mysql
    ports:
      - "3306:3306"

